#!/data/data/com.termux/files/usr/bin/bash
clear
echo "           __     _           _     _ ";
echo "__      __/ _| __| |_ __ ___ (_) __| |";
echo "\ \ /\ / / |_ / _  | '__/ _ \| |/ _  |";
echo " \ V  V /|  _| (_| | | | (_) | | (_| |";
echo "  \_/\_/ |_|  \__,_|_|  \___/|_|\__,_|";
echo "##############################";
echo "Recoded By 0x404              ";
echo "DikyyPratama                  ";
echo "phallepy@gmail.com            ";
echo "";
echo "1. Web Source-Code Viewer";
echo "2. Web Brute Force";
echo "3. Web Login Finder";
echo "00. Upgrade";
echo "88. Credits";
echo -ne "\n@=> ";read menu

  if [ $menu == '88' ]
  then
     clear
     echo "           __     _           _     _ ";
     echo "__      __/ _| __| |_ __ ___ (_) __| |";
     echo "\ \ /\ / / |_ / _  | '__/ _ \| |/ _  |";
     echo " \ V  V /|  _| (_| | | | (_) | | (_| |";
     echo "  \_/\_/ |_|  \__,_|_|  \___/|_|\__,_|";
     echo "             Recoded by 0x404         ";
     echo "";
     echo "";
     sleep 5s
  elif [ $menu == '1' ]
  then
     /data/data/com.termux/files/usr/share/wfdroid/sourcecode

  elif [ $menu == '2' ]
  then
     /data/data/com.termux/files/usr/share/wfdroid/webbrute

  elif [ $menu == '3' ]
  then
     /data/data/com.termux/files/usr/share/wfdroid/loginfinder

  elif [ $menu == '4' ]
  then
     /data/data/com.termux/files/usr/share/wfdroid/wordlist

  elif [ $menu == '00' ]
  then
     /data/data/com.termux/files/usr/share/wfdroid/update

  else
     echo "You must choose menu with a number."

  fi
